= Species Occurrence Cube SQL Functions

These custom functions have been developed by the B-Cubed project for producing species occurrence cubes.

See xref:generate-cube-databricks.adoc[] for an example of their usage.

== Grid functions

These functions are usually used for generating species occurrence cubes. They calculate a grid cell for a point.

=== EEA Reference Grid cell code

*Suggested function declaration:*

[source, sql]
----
CREATE OR REPLACE TEMPORARY FUNCTION eeaCellCode AS 'org.gbif.occurrence.hive.udf.EeaCellCodeUDF';
----

*Function definition:*

[source, sql]
----
STRING eeaCellCode(INTEGER gridSize,
                   DOUBLE latitude,
                   DOUBLE longitude,
                   DOUBLE coordinateUncertaintyInMeters)
----

*Parameters:*

`gridSize`:: The _grid size_ in metres of the EEA Reference Grid. Must be _25_, _100_, _250_, _1000_, _10000_ or _100000_.
`latitude`:: The latitude of the _point_ to grid (usually the `decimalLatitude` field)
`longitude`:: The longitude of the _point_ to grid (usually the `decimalLongitude` field)
`coordinateUncertaintyInMeters`:: The uncertainty radius to apply to the _point_ (usually used with a default value, for example `COALESCE(coordinateUncertaintyInMeters, 1000)`)

The _coordinateUncertaintyInMeters_ value is used to randomize the _point_ within the circle.

*Return value:*

The code for the cell of the EEA reference grid in which the randomized point falls.

*Example arguments and returned values:*

[cols=">,>,>,>,>"]
|===
|Result|_gridSize_|_latitude_|_longitude_|_coordinateUncertaintyInMeters_
|`100kmE43N32`|`100 000`|`52.0`|`10.0`|`1000.0`
|`10kmE432N321`|`10 000`|`52.0`|`10.0`|`1000.0`
|`1kmE4321N3210`|`1 000`|`52.0`|`10.0`|`1000.0`
|`250mE432100N321000`|`250`|`52.0`|`10.0`|`1000.0`
|`100mE43210N32100`|`100`|`52.0`|`10.0`|`1000.0`
|`25mE4321000N3210000`|`25`|`52.0`|`10.0`|`1000.0`
|===

GeoPackage and ShapeFile downloads of the grids at several resolutions are available for download at the https://www.eea.europa.eu/en/datahub/datahubitem-view/3c362237-daa4-45e2-8c16-aaadfb1a003b[European Environment Agency Datahub]. (See the 2013 and 2011 datasets for alternative resolutions.)

Reference: https://sdi.eea.europa.eu/catalogue/srv/api/records/aac8379a-5c4e-445c-b2ef-23a6a2701ef0/attachments/eea_reference_grid_v1.pdf[About the EEA reference grid (PDF)].

=== Extended Quarter-Degree Grid cell code

*Suggested function declaration:*

[source, sql]
----
CREATE OR REPLACE TEMPORARY FUNCTION eqdgcCode AS 'org.gbif.occurrence.hive.udf.ExtendedQuarterDegreeGridCellCodeUDF';
----

*Function definition:*

[source, sql]
----
STRING eqdgcCode(INTEGER level,
                 DOUBLE latitude,
                 DOUBLE longitude,
                 DOUBLE coordinateUncertaintyInMeters)
----

*Parameters:*

`level`:: The _level_ of the grid; the number of additional divisions applied to a one-degree cell.
`latitude`:: The latitude of the _point_ to grid (usually the `decimalLatitude` field)
`longitude`:: The longitude of the _point_ to grid (usually the `decimalLongitude` field)
`coordinateUncertaintyInMeters`:: The uncertainty radius to apply to the _point_ (usually used with a default value, for example `COALESCE(coordinateUncertaintyInMeters, 1000)`)

The _coordinateUncertaintyInMeters_ value is used to randomize the _point_ within the circle.

A _level_ of _0_ will give the 1° cell, e.g. `S01E010`. For quarter-degrees, use _level_ _2_, e.g. `S01E010AD`.

*Return value:*

The code for the cell of the Extended Quarter-Degree Grid in which the randomized point falls.

*Example arguments and returned values:*

[cols=">,>,>,>,>"]
|===
|Result|_level_|_latitude_|_longitude_|_coordinateUncertaintyInMeters_
|`E010N52`|`0`|`52.3`|`10.3`|`1000.0`
|`E010N52C`|`1`|`52.3`|`10.3`|`1000.0`
|`E010N52CB`|`2`|`52.3`|`10.3`|`1000.0`
|`E010N52CBC`|`3`|`52.3`|`10.3`|`1000.0`
|`E010N52CBCC`|`4`|`52.3`|`10.3`|`1000.0`
|`E010N52CBCCB`|`5`|`52.3`|`10.3`|`1000.0`
|`E010N52CBCCBB`|`6`|`52.3`|`10.3`|`1000.0`
|===

Reference: https://doi.org/10.1111/j.1365-2028.2008.00997.x[Larsen R, Holmern T, Prager SD, Maliti H, Røskaft, E. (2009) Using the extended quarter degree grid cell system to unify mapping and sharing of biodiversity data. African Journal of Ecology, 47: 382-392.]

See also: https://en.wikipedia.org/wiki/QDGC[Wikipedia: QDGC].

=== ISEA3H Grid cell code

This function implements the _Inverse Snyder Equal-Area Projection (ISEA) Aperture 3 Hexagonal (3H) Discrete Global Grid System (DGGS)_, ISEA3H. Grid cell codes/identifiers are as specified in https://doi.org/10.1080/15230406.2018.1455157[A novel identifier scheme for the ISEA Aperture 3 Hexagon Discrete Global Grid System].

*Suggested function declaration:*

[source, sql]
----
CREATE OR REPLACE TEMPORARY FUNCTION isea3hCode AS 'org.gbif.occurrence.hive.udf.Isea3hCellCodeUDF';
----

*Function definition:*

[source, sql]
----
STRING isea3hCode(INTEGER resolution,
                  DOUBLE latitude,
                  DOUBLE longitude,
                  DOUBLE coordinateUncertaintyInMeters)
----

*Parameters:*

`resolution`:: The _resolution_ of the grid; the number of division steps applied to the initial dodecahedron. Valid values are 1 to 22.
`latitude`:: The latitude of the _point_ to grid (usually the `decimalLatitude` field)
`longitude`:: The longitude of the _point_ to grid (usually the `decimalLongitude` field)
`coordinateUncertaintyInMeters`:: The uncertainty radius to apply to the _point_ (usually used with a default value, for example `COALESCE(coordinateUncertaintyInMeters, 1000)`)

The _coordinateUncertaintyInMeters_ value is used to randomize the _point_ within the circle.

See https://cran.r-project.org/web/packages/dggridR/vignettes/dggridR.html[ISEA3H details] for the number and size of cells at each resolution.

*Return value:*

The code for the cell of the ISEA3H grid cell in which the randomized point falls.

*Example arguments and returned values:*

[cols=">,>,>,>,>"]
|===
|Result|_resolution_|_latitude_|_longitude_|_coordinateUncertaintyInMeters_
|`-358282526011250000`|`3`|`52.3`|`10.3`|`1000.0`
| `652180731009071912`|`6`|`52.3`|`10.3`|`1000.0`
| `952458899010519815`|`9`|`52.3`|`10.3`|`1000.0`
|===

References:

* http://www.opengis.net/doc/AS/dggs/1.0[Discrete Global Grid Systems Abstract Specification]
* https://doi.org/10.1559/152304003100011090[Geodesic discrete global grid systems.]
* https://doi.org/10.1080/15230406.2018.1455157[A novel identifier scheme for the ISEA Aperture 3 Hexagon Discrete Global Grid System]

See also:

* https://github.com/mocnik-science/geogrid[geogrid], the Java library used by GBIF to calculate the grid.
* https://cran.r-project.org/web/packages/dggridR/vignettes/dggridR.html[dggridR], an R package to calculate the grid (though not using the same identifiers).

=== Military Grid Reference System cell code

*Suggested function declaration:*

[source, sql]
----
CREATE OR REPLACE TEMPORARY FUNCTION mgrsCode AS 'org.gbif.occurrence.hive.udf.MilitaryGridReferenceSystemCellCodeUDF';
----

*Function definition:*

[source, sql]
----
STRING mgrsCode(INTEGER gridSize,
                DOUBLE latitude,
                DOUBLE longitude,
                DOUBLE coordinateUncertaintyInMeters)
----

*Parameters:*

`gridSize`:: The _grid size_ in metres. Must be _1_, _10_, _100_, _1000_, _10000_, _100000_ or _0_.
`latitude`:: The latitude of the _point_ to grid (usually the `decimalLatitude` field)
`longitude`:: The longitude of the _point_ to grid (usually the `decimalLongitude` field)
`coordinateUncertaintyInMeters`:: The uncertainty radius to apply to the _point_ (usually used with a default value, for example `COALESCE(coordinateUncertaintyInMeters, 1000)`)

The _coordinateUncertaintyInMeters_ value is used to randomize the _point_ within the circle.

A _gridSize_ of _0_ will give the Grid Zone Junction (GZJ) only, e.g. `32`. Other values increase the accuracy of the grid, e.g. _100_ (metres) `32UNC686615`.

*Return value:*

The code for the cell of the Military Grid Reference System in which the randomized point falls.

*Example arguments and returned values:*

[cols=">,>,>,>,>"]
|===
|Result|_gridSize_|_latitude_|_longitude_|_coordinateUncertaintyInMeters_
|`32U`|`0`|`52.0`|`10.0`|`1000.0`
|`32UNC`|`100 000`|`52.0`|`10.0`|`1000.0`
|`32UNC66`|`10 000`|`52.0`|`10.0`|`1000.0`
|`32UNC6861`|`1 000`|`52.0`|`10.0`|`1000.0`
|`32UNC686615`|`100`|`52.0`|`10.0`|`1000.0`
|`32UNC68646151`|`10`|`52.0`|`10.0`|`1000.0`
|`32UNC6864961510`|`1`|`52.0`|`10.0`|`1000.0`
|===

Reference: https://earth-info.nga.mil/GandG/coordsys/grids/referencesys.html[Grids and Reference Systems].

See also: https://en.wikipedia.org/wiki/Military_Grid_Reference_System[Wikipedia: Military Grid Reference System].

=== Temporal Uncertainty

*Suggested function declaration:*

[source, sql]
----
CREATE OR REPLACE TEMPORARY FUNCTION temporalUncertainty AS 'org.gbif.occurrence.hive.udf.TemporalUncertaintyUDF';
----

*Function definition:*

[source, sql]
----
STRING temporalUncertainty(String dateInterval)
----

*Parameters:*

`dateInterval`:: A string containing an ISO-8106 date or date interval.

*Return value:*

This function returns the uncertainty in seconds of the date.

*Example arguments and returned value*

|===
|_dateInterval_ |Result |Remarks
|2021-03-21T15:01:32.456Z |1 |Milliseconds are rounded to seconds.
|2021-03-21T15:01:32Z |1 |
|2021-03-21T15:01Z |60 |
|2021-03-21T15Z |60×60 |
|2021-03-21 |60×60×24 |
|2021-03-01 |60×60×24 |
|2021-01-01 |60×60×24 |
|2021-03 |60×60×24×31 |
|2021 |60×60×24×365 |
|2021-03-21/2021-03-23 |60×60×24×3 |
|===

== Software repository

Source code for the functions is available https://github.com/gbif/occurrence-cube[on GitHub].

Compiled code is available from https://repository.gbif.org/service/rest/repository/browse/releases/org/gbif/occurrence/cube-functions/[GBIF's repository]; choose the latest version and download `cube-functions-<VERSION>.jar`.
