= API SQL Downloads

NOTE: This is an **experimental feature**, and the implementation may change throughout 2024.  The feature is currently only available for preview by invited users.

The experimental Occurrence SQL Download API allows users to query GBIF occurrences using SQL, _structured query language_, a programming language commonly used to access database systems.  In contrast to the xref:api-downloads.adoc[Predicate Download API], the SQL API allows selection of the columns of interest and generating summary views of the data.  Functions to generate _data cubes_ are available, as part of the https://b-cubed.eu/[Biodiversity Building Blocks for Policy] ("B-Cubed") project.

Occurrence SQL downloads are created asynchronously — the user requests a download and, once the download is prepared, is sent an email with a link to the resulting file.

It is necessary to register as a user on https://www.gbif.org/[GBIF.org] to create an SQL download request, and to authenticate using the username (not the email) and password.

// Complete technical details are provided in the xref:v1@openapi::occurrence.adoc#/tag/Occurrence-downloads[API reference documentation].

Using this API requires some knowledge of SQL.  Many general tutorials and guides to writing SQL queries are online, for example http://datacarpentry.org/sql-ecology-lesson/[Data management with SQL for Ecologists] (by Data Carpentry), see particularly the section on http://datacarpentry.org/sql-ecology-lesson/02-sql-aggregation.html[aggregating and grouping data].

We will create a user interface for common types of query (e.g. data cubes) during 2024.

== Requesting an SQL occurrence download

A download request includes your username, email address, the download format, and the filter for the required data in the form of an SQL statement.

A basic example using the _curl_ command to make the request:

Put this in a file called `query.json`:

[source,json]
----
{
  "creator": "userName", <1>
  "notificationAddresses": [
    "userEmail@example.org" <2>
  ],
  "sendNotification": True,
  "format": "SQL_TSV_ZIP", <3>
  "sql": "SELECT datasetKey, countryCode, COUNT(*) FROM occurrence WHERE continent = 'EUROPE' GROUP BY datasetKey, countryCode" <4>
}
----
<1> Replace with your username
<2> Replace with your email address, or remove the `notificationAddresses` section and set `sendNotification` to `false`
<3> `format` must be `SQL_TSV_ZIP`.  More formats will be added later.
<4> This query will count occurrences from Europe per dataset and country.

Then use this Curl command:

[source,shell]
----
curl --include --user userName:PASSWORD --header "Content-Type: application/json" --data @query.json https://api.gbif.org/v1/occurrence/download/request
----

A download key is returned. Querying that download key shows the download information, including the download link and DOI once the download is ready.  Run this repeatedly, until you see `SUCCEEDED` — you will need to use your download key rather than the example:

[source,shell]
----
curl -Ss https://api.gbif.org/v1/occurrence/download/0000379-240229165702484
----

You can then download the resulting file:

[source,shell]
----
curl --location --remote-name https://api.gbif.org/v1/occurrence/download/0000379-240229165702484.zip
----

And see the result:

[%header,format=tsv]
|===
datasetkey	countrycode	COUNT(*)
005eb8d8-ed94-41be-89cf-e3115a9058e4	AD	1
009a76f6-0960-4a56-a116-63991e6bb037	GR	3
0214a6a7-898f-4ee8-b888-0be60ecde81f	PT	84
03f2256a-e548-43d7-a731-253302f4aa34	LV	27
040c5662-da76-4782-a48e-cdea1892d14c	IS	1306
06aeea22-c116-4df2-93af-2d8321482801	FR	24
07fd0d79-4883-435f-bba1-58fef110cd13	PL	357
|===

[#sql]
== Supported SQL

Only `SELECT` queries are supported, and only queries against a single table, `occurrence`.  `JOIN` queries and sub-queries are not allowed.  Selecting `*` is also not allowed, specify the columns you need.

`GROUP BY` queries are supported, but not `HAVING` clauses.

Most common SQL operators and functions are supported, such as `AND`, `OR`, `NOT`, `IS NULL`, `RAND()`, `ROUND(…)`, `LOWER(…)`, etc.

Aggregate functions are also supported, for example `COUNT(…)`, `MIN(…)`, `MAX(…)`, `AVERAGE(…)`.

Several custom functions are available:

* `gbif_geoDistance`
* `gbif_joinArray`
* `gbif_toISO8601`
* `gbif_toLocalISO8601`

As well as custom aggregate functions:

* `gbif_eeargCode`

See the xref:api-sql-download-functions.adoc[separate page on the available SQL functions].

[#sql-columns]
== Available columns

The `occurrence` table contains the interpreted data, the verbatim (as provided to GBIF) data, and some calculated columns useful for searching.  The full list of available columns is show below, and is also available through https://api.gbif.org/v1/occurrence/download/describe/sql[this API call] — the `name` field is the column name.  Note the `v_` prefix for the verbatim data columns.

.Full list of available SQL column names
[%collapsible]
====
The definitions marked with {dwc_source} are from the Darwin Core standard.

The definitions marked with {gbif_source} are from GBIF, and may reflect the result of interpretation and data quality procedures applied by GBIF, or they may not be part of Darwin Core.

include::partial$download-sql-terms-table.adoc[]
====

The SQL parser is strict, and column names that are also SQL keywords must be quoted. For example, `"year"`, `"month"` and `"day"`.

[#sql-validation]
== Query validation

You can validate your queries using the validation API call.

[source,shell]
----
curl --include --header "Content-Type: application/json" --data @query.json https://api.gbif.org/v1/occurrence/download/request/validate
----

Your query will be returned if it is valid, and an error message with an explanation will be returned if it is invalid.

[#cube]
== Data cube example

Data cubes are views of GBIF occurrence data, filtered and summarized by species, time and location, and providing measures for each dimension.

This detailed query applies several quality filters for data for occurrences in Slovenia recorded since 2000.  It produces a summary by year of observation/collection, species and the https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/about-the-eea-reference-grid/eea_reference_grid_v1.pdf/at_download/file[EEA Reference Grid (PDF)] using a 1km grid size.  For each row, the minimum coordinate uncertainty is given.

[source,sql]
----
SELECT
  "year",
  gbif_eeargCode(1000, decimalLatitude, decimalLongitude, COALESCE(coordinateUncertaintyInMeters, 1000)) AS eeaCellCode,
  speciesKey,
  COUNT(*) AS count,
  MIN(COALESCE(coordinateUncertaintyInMeters, 1000)) AS minCoordinateUncertaintyInMeters
FROM occurrence
WHERE
      occurrenceStatus = 'PRESENT'
  AND speciesKey IS NOT NULL
  AND NOT array_contains(issue, 'ZERO_COORDINATE')
  AND NOT array_contains(issue, 'COORDINATE_OUT_OF_RANGE')
  AND NOT array_contains(issue, 'COORDINATE_INVALID')
  AND NOT array_contains(issue, 'COUNTRY_COORDINATE_MISMATCH')
  AND (identificationVerificationStatus IS NULL
       OR NOT (   LOWER(identificationVerificationStatus) LIKE '%unverified%'
               OR LOWER(identificationVerificationStatus) LIKE '%unvalidated%'
               OR LOWER(identificationVerificationStatus) LIKE '%not able to validate%'
               OR LOWER(identificationVerificationStatus) LIKE '%control could not be conclusive due to insufficient knowledge%'
               OR LOWER(identificationVerificationStatus) LIKE '%unconfirmed%'
               OR LOWER(identificationVerificationStatus) LIKE '%unconfirmed - not reviewed%'
               OR LOWER(identificationVerificationStatus) LIKE '%validation requested%'
              )
      )
  AND countryCode = 'SI'
  AND "year" >= 2000
  AND hasCoordinate
GROUP BY "year", eeaCellCode, speciesKey
ORDER BY "year" DESC, eeaCellCode ASC, speciesKey ASC;
----

New line characters cannot be used in the JSON file used to make the API query, and the `"` characters within the query must be escaped with a backslash `\`:

[source,json]
----
{
  "creator": "userName",
  "sendNotification": false,
  "format": "SQL_TSV_ZIP",
  "sql": "SELECT \"year\", gbif_eeargCode(1000, decimallatitude, decimallongitude, COALESCE(coordinateUncertaintyInMeters, 1000)) AS eeaCellCode, speciesKey, COUNT(*) AS \"count\", MIN(COALESCE(coordinateUncertaintyInMeters, 1000)) AS \"minCoordinateUncertaintyInMeters\" FROM occurrence WHERE occurrenceStatus = 'PRESENT' AND speciesKey IS NOT NULL NOT array_contains(issue, 'ZERO_COORDINATE') AND NOT array_contains(issue, 'COORDINATE_OUT_OF_RANGE') AND NOT array_contains(issue, 'COORDINATE_INVALID') AND NOT array_contains(issue, 'COUNTRY_COORDINATE_MISMATCH') AND (identificationVerificationStatus IS NULL OR NOT (LOWER(identificationVerificationStatus) LIKE '%unverified%' OR LOWER(identificationVerificationStatus) LIKE '%unvalidated%' OR LOWER(identificationVerificationStatus) LIKE '%not able to validate%' OR LOWER(identificationVerificationStatus) LIKE '%control could not be conclusive due to insufficient knowledge%' OR LOWER(identificationVerificationStatus) LIKE '%unconfirmed%' OR LOWER(identificationVerificationStatus) LIKE '%unconfirmed - not reviewed%' OR LOWER(identificationVerificationStatus) LIKE '%validation requested%')) AND countryCode = 'SI' AND \"year\" >= 2000 AND hasCoordinate GROUP BY \"year\", eeaCellCode, speciesKey ORDER BY \"year\" DESC, eeaCellCode ASC, speciesKey ASC"
}
----

The query can be validated and submitted as described above.
