= Occurrence download formats

Data downloads are available from GBIF in three primary formats:

* <<simple,*Simple*>>.  This format contains a selection of commonly used terms, after the data has been aligned to GBIF's taxonomic and geographic indices and structured vocabularies
** Downloads created on www.gbif.org or through the API using the format `SIMPLE_CSV` are produced in a tab-separated text format, suitable for use with spreadsheets and programming/scripting languages
** Occurrence data accessed through xref:cloud-services.adoc[cloud services], or with the API format `SIMPLE_PARQUET`, are produced in https://en.wikipedia.org/wiki/Apache_Parquet[Apache Parquet format].  The fields are the same as for tab-separated text format.
* <<dwca,*Darwin Core Archive*>> (API: `DWCA`).  This is a compressed Zip file, containing data in tab-separated text format, and metadata in XML format.
** `occurrence.txt` contains occurrence data after interpretation by GBIF's systems.
** `multimedia.txt` contains information on multimedia (images, audio, video) relating to the occurrences.
** `verbatim.txt` contains the original, uninterpreted data, without modifications by GBIF's systems.
* <<species-list,*Species List*>> (API: `SPECIES_LIST`).  This is a summary format containing the distinct list of species names returned by the filter.

The header row (first row) of all these files contain the short name of the terms they contain.  Most of the terms are defined by the https://dwc.tdwg.org/terms/[Darwin Core standard].  For example, the column `catalogNumber` contains data of the Darwin Core term https://rs.tdwg.org/dwc/terms/catalogNumber[http://rs.tdwg.org/dwc/terms/catalogNumber].

[#simple]
== Simple download – Term definitions

include::partial$download-simple-terms-table.adoc[]

[#dwca]
== DWCA downloads

Darwin Core Archive downloads from gbif.org contain the following files:

`occurrence.txt`:: Occurrence data after interpretation by GBIF.  Described in detail <<dwca-interpreted,below>>.
`multimedia.txt`:: Occurrence multimedia data after interpretation by GBIF. #Not yet defined.#
`verbatim.txt`:: Occurrence data without interpretation by GBIF.  Described in detail <<dwca-verbatim,below>>.
`meta.xml`:: The https://dwc.tdwg.org/text/[Darwin Core Archive metafile], describing the structure of the archive — the file formats, column names and their terms.
`metadata.xml`:: Metadata about the download in https://eml.ecoinformatics.org/[Ecological Metadata Language (EML)].
`rights.txt`:: Licence information for all the datasets with occurrences in the download.
`citations.txt`:: Citations for all the datasets with occurrences in the download.
`dataset/*.xml`:: EML metadata for every dataset with occurrences in the download.

The data can be read without any special tools, but there are also libraries to read Darwin Core Archives in these programming languages:

* Java — https://github.com/gbif/dwca-io[GBIF dwca-io]
* #Python?#
* #R?#
* #Ruby?#
* #...?#

#TODO:# Many of the undefined terms are not part of Darwin Core, and shouldn't be present in downloads. See https://github.com/gbif/occurrence/issues/294[issue].

#TODO 2:# From where should the GBIF term definitions come?

#TODO 3:# Could verbatim and interpreted be combined?

#TODO 4:# The https://api.gbif.org/v1/occurrence/download/describe/dwca[API call] doesn't include multimedia, or any of the verbatim extensions.

#TODO 5:# Some of these terms deserve comments on specific GBIF usage, e.g. separators.

#TODO 6:# There are trailing underscores on some of the field names, that's a bug in the API.

[#dwca-interpreted]
=== Interpreted term definitions (`occurrence.txt`)

include::partial$download-dwca-interpreted-terms-table.adoc[]

[#dwca-verbatim]
=== Verbatim term definitions (`verbatim.txt`)

include::partial$download-dwca-verbatim-terms-table.adoc[]

[species-list]
== Species list downloads – Term definitions

include::partial$download-simple-terms-table.adoc[]
