= rgbif

_An interface to the GBIF API for the R statistical programming environment._

**rgbif** is an R package from https://ropensci.org/[rOpenSci] that allows searching and retrieving data from GBIF. rgbif wraps R code around the xref:api-introduction.adoc[GBIF API] to allow you to talk to GBIF from R and access metadata, species names, and occurrences.

The main rgbif documentation can be found https://docs.ropensci.org/rgbif/index.html[here].

== Installation

[source,r]
----
install.packages("rgbif") # CRAN version
----

[source,r]
----
pak::pkg_install("ropensci/rgbif") # dev version
----

[source,r]
----
install.packages("rgbif", repos="https://dev.ropensci.org") # dev version
----

== Getting Started 

There are several long-form articles that can help get you started:

* https://docs.ropensci.org/rgbif/articles/rgbif.html[Getting Started]
* https://docs.ropensci.org/rgbif/articles/getting_occurrence_data.html[Getting Occurrence Data From GBIF]
* https://docs.ropensci.org/rgbif/articles/taxonomic_names.html[Working With Taxonomic Names]

Most GBIF users are interested in getting lat-lon occurrence records. 

[source,r]
----
occ_search(scientificName = "Pan troglodytes")
occ_data(scientificName = "Pan troglodytes")
----

It is usually better to get occurrence records using a **taxonKey**. See the article https://docs.ropensci.org/rgbif/articles/taxonomic_names.html[Working With Taxonomic Names]. 

[source,r]
----
taxonKey <- name_backbone("Pan troglodytes")$usageKey
occ_search(taxonKey = taxonKey)
----

GBIF **strongly recommends** the use of ``occ_download()`` rather than ``occ_search()`` for serious research projects. See article https://docs.ropensci.org/rgbif/articles/getting_occurrence_data.html[Getting Occurrence Data From GBIF]. 

It is required to set up your https://docs.ropensci.org/rgbif/articles/gbif_credentials.html[GBIF credentials] to make downloads from GBIF. 

[source,r]
----
occ_download(pred("taxonKey", 5219534)) # 5219534 is the taxonKey for Pan troglodytes
----

== Citation 

Under the terms of the GBIF data user agreement, users who download data agree to cite a DOI. Please see GBIF’s https://www.gbif.org/citation-guidelines[citation guidelines] and https://docs.ropensci.org/rgbif/articles/gbif_citations.html[Citing GBIF Mediated Data].

Please also cite **rgbif** by running ``citation(package = "rgbif")``.

