= rgbif

_An interface to the GBIF API for the R statistical programming environment._

rgbif is an R package from https://ropensci.org/[rOpenSci] that allows searching and retrieving data from GBIF. rgbif wraps R code around the xref:api-introduction.adoc[GBIF API] to allow you to talk to GBIF from R and access metadata, species names, and occurrences.

## Installation

[source,r]
----
> install.packages("rgbif") # CRAN version
----

[source,r]
----
> pak::pkg_install("ropensci/rgbif") # dev version
----

[source,r]
----
> install.packages("rgbif", repos="https://dev.ropensci.org") # dev version
----

## Getting Started 

There are several long-form articles that can help get you started:

* [Getting Started](https://docs.ropensci.org/rgbif/articles/rgbif.html)
* [Getting Occurrence Data From GBIF](https://docs.ropensci.org/rgbif/articles/getting_occurrence_data.html)
* [Working With Taxonomic Names](https://docs.ropensci.org/rgbif/articles/taxonomic_names.html)

Most GBIF users are interested in getting lat-lon occurrence records. 

[source,r]
----
> occ_search(scientificName = "Pan troglodytes")
> occ_data(scientificName = "Pan troglodytes")
```

It is usually better to get occurrence records using a **taxonKey**. See the article [Working With Taxonomic Names](https://docs.ropensci.org/rgbif/articles/taxonomic_names.html). 

[source,r]
----
> taxonKey <- name_backbone("Pan troglodytes")$usageKey
> occ_search(taxonKey = taxonKey)
----

GBIF **strongly recommends** the use of `occ_download()` rather than `occ_search()` for serious research projects. See article [Getting Occurrence Data From GBIF](https://docs.ropensci.org/rgbif/articles/getting_occurrence_data.html). 

It is required to set up your [GBIF credentials](https://docs.ropensci.org/rgbif/articles/gbif_credentials.html) to make downloads from GBIF. 

[source,r]
----
> occ_download(pred("taxonKey", 5219534)) # 5219534 is the taxonKey for Pan troglodytes
----


## Citation 

Under the terms of the GBIF data user agreement, users who download data agree to cite a DOI. Please see GBIF’s [citation guidelines](https://www.gbif.org/citation-guidelines) and [Citing GBIF Mediated Data](https://docs.ropensci.org/rgbif/articles/gbif_citations.html).

Please also cite **rgbif** by running `citation(package = "rgbif")`.


-------------------------------------------------------------------------------------------------------------

_An interface to the GBIF API for the R statistical programming environment._

rgbif is an R package from https://ropensci.org/[rOpenSci] that allows searching and retrieving data from GBIF. rgbif wraps R code around the xref:api-introduction.adoc[GBIF API] to allow you to talk to GBIF from R and access metadata, species names, and occurrences.

Installing the package in R is simple:

[source,r]
----
> install.packages("rgbif")
----

Once installed, rgbif allows you to easily

* get data for single occurrences
* retrieve multiple occurrences
* search for taxon names
* generate maps of occurrences

Full functionality is described in the https://docs.ropensci.org/rgbif/[rgbif tutorial].  The rgbif package is also part of the https://github.com/ropensci/spocc[SPOCC Species Occurrence Data suite], which provides access to occurrence records from multiple databases.

== Citing data retrieved via rgbif

NOTE: GBIF recommend using a https://www.gbif.org/citation-guidelines#derivedDatasets[derived dataset] for citing data obtained using synchronous API calls as used by rgbif in _occ_data()_ and _occ_search()_.

For data obtained using the _occ_download()_ routes, _gbif_citation()_ can be used to retrieve the DOI.

The *rgbif* library includes a function, _gbif_citation()_, that will help you properly cite the data downloaded from GBIF. To use, simply pass either a single occurrence key, a dataset key, or the results of a call to the _occ_download_get_ functions.

Examples:

.Write CSV file containing summary of datasets to use with the https://www.gbif.org/derived-dataset/register[Derived Dataset tool]
[source,r]
----
> myData<-occ_data(taxonKey=10709636)
> datasetCounts<-myData$data %>% count(datasetKey, sort=TRUE)
> write.table(datasetCounts, "~/derivedDatasetCounts.txt",col.names=FALSE, row.names=FALSE,sep=",")
----

.Get citation for a single occurrence, passing the occurrence key as an argument
[source,r]
----
> gbif_citation(x=1265576727)
<<rgbif citation>>
   Citation: iNaturalist.org (2017). iNaturalist Research-grade Observations.
        Occurrence Dataset https://doi.org/10.15468/ab3s5x accessed via
        GBIF.org on 2017-10-25.. Accessed from R via rgbif
        (https://github.com/ropensci/rgbif) on 2017-10-25
   Rights:
----

.Get citation for a dataset, passing the dataset key as an argument
[source,r]
----
> gbif_citation(x='d52d01f6-7472-4dbf-9ea8-a33c343255ac')
<<rgbif citation>>
   Citation: Moeslund J E (2016). Vegetation data from protected areas in
        Denmark (§ 3 in the Danish Nature Protection Act). Version 8.1.
        Department of Bioscience, Aarhus University. Occurrence Dataset
        https://doi.org/10.15468/ar7pbr accessed via GBIF.org on 2017-10-25..
        Accessed from R via rgbif (https://github.com/ropensci/rgbif) on
        2017-10-25
   Rights:
----

.Get citation for asynchronous downloads, passing the results of a call to the _occ_download_get_ function:
[source,r]
----
> my_download<-occ_download_get("0005737-171002173027117",overwrite=TRUE)
Download file size: 0.26 MB
On disk at /tmp/0005737-171002173027117.zip
> gbif_citation(my_download)
$download
[1] "GBIF Occurrence Download https://doi.org/10.15468/dl.j0ehrr Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2017-10-18"

...
----

This response will also include individual citations of contributing datasets, however, the above citation containing the DOI will include references to each of these including information about which specific occurrences were included in the download.

.Get citation for downloads, passing the results of a call to the occ_download_meta function:
[source,r]
----
> my_download_metadata<-occ_download_meta("0005737-171002173027117")
> gbif_citation(my_download_metadata)
$download
[1] "GBIF Occurrence Download https://doi.org/10.15468/dl.j0ehrr Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2017-10-18"
...
----

=== Citation

Scott Chamberlain (2017). rgbif: Interface to the Global 'Biodiversity' Information Facility 'API'. R package version 0.9.8. https://CRAN.R-project.org/package=rgbif
