site:
  title: GBIF Technical Documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://tech-docs.gbif-dev.org
content:
  sources:
    - url: ~/dev/git/gbif/tech-docs
      start_path: components/test
      branches: main
    - url: ~/dev/git/gbif/tech-docs
      start_path: components/guides
      branches: main
    - url: https://gitlab.com/antora/demo/demo-component-a.git
      branches: master
      # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
      # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
      edit_url: false
    #- url: https://gitlab.com/antora/demo/demo-component-b.git
    #  branches: [v2.0, v1.0]
    #  start_path: docs
    - url: git@github.com:LiskHQ/lisk-docs.git
      branches: docs-sdk
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    #snapshot: true  
    url: ./theme/build/ui-bundle.zip
    snapshot: true
