site:
  title: GBIF Technical Documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://tech-docs.gbif-dev.org
  start_page: overview::index.adoc
content:
  sources:
    - url: ./
      start_path: components/overview
      branches: HEAD
    - url: ./
      start_path: components/openapi
      branches: main
    - url: ./
      start_path: components/guides
      branches: main
    - url: git@github.com:gbif/ipt.git
      branches: [ipt-2.4.2-docs, dev]
      start_path: docs/en
ui:
  bundle:
    url: ./theme/build/ui-bundle.zip
  supplemental_files: ./supplemental_ui
