site:
  title: GBIF Technical Documentation
  start_page: ROOT::index.adoc
  keys:
    language: en
content:
  sources:
    - url: .
      start_path: ./en/home
      branches: HEAD
    - url: .
      start_path: ./en/data-publishing
      branches: HEAD
    - url: .
      start_path: ./en/data-use
      branches: HEAD
    - url: .
      start_path: ./en/openapi
      branches: HEAD
    - url: .
      start_path: ./en/guides
      branches: HEAD
    - url: git@github.com:gbif/ipt.git
      branches: [ipt-2.4-docs, ipt-2.5-docs, master]
      start_path: docs/en
    - url: git@github.com:MattBlissett/doc-data-pipelines-for-biodiversity-data.git
      start_path: en
      branches: HEAD
    - url: git@github.com:gbif/doc-publishing-dna-derived-data.git
      start_path: en
      branches: antora
output:
  clean: true
  dir: ./output/en
runtime:
  fetch: false
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    page-pagination: yes
    language: en
    null: ␀
