// DOI badge: If you have a DOI, remove the comment ("// ") from the line below, change "10.EXAMPLE/EXAMPLE" to the DOI in all three places, and remove this line.
// https://doi.org/10.EXAMPLE/EXAMPLE[image:https://zenodo.org/badge/DOI/10.EXAMPLE/EXAMPLE.svg[doi:10.EXAMPLE/EXAMPLE]]
// License badge
//https://creativecommons.org/licenses/by-sa/4.0/[image:https://img.shields.io/badge/License-CC%20BY%2D-SA%204.0-lightgrey.svg[CC BY-SA 4.0]]
// Build status badge
https://builds.gbif.org/job/tech-docs/lastBuild/console[image:https://builds.gbif.org/job/tech-docs/badge/icon[Build status]]
// Translation badge
https://crowdin.com/project/gbif-tech-docs[image:https://badges.crowdin.net/gbif-tech-docs/localized.svg[Localization status]]

= GBIF Technical Documentation

This is the the https://techdocs.gbif.org/[GBIF technical documentation site], visible at https://techdocs.gbif.org/.

The development site is visible at https://techdocs.gbif-uat.org/

NOTE: This file is documenting the documentation system, it's not shown on https://techdocs.gbif.org/.

== Overall structure

The document system uses https://docs.antora.org/[Antora], a framework for combining documentation written in https://docs.asciidoctor.org/asciidoc/latest/[Asciidoctor] from multiple Git repositories into a single documentation website.

=== Languages, components, versions and modules

Antora strictly defines how files and directories should be arranged, but is flexible in allowing those files and directories to come from various sources.  There are four levels of content:

Languages:: (GBIF addition, but following the https://gitlab.com/antora/antora/-/issues/208[suggestion on the Antora issue tracker]).  We don't expect all the manual to be translated into every language, so we should structure content to make it easy for translators to translate (and see progress) for suitable topics without being overwhelmed.
Components:: The largest blocks of documentation.  Components we have include https://techdocs.gbif.org/en/data-publishing/[_Data Publishing_] and the https://techdocs.gbif.org/en/openapi/[_API reference_].
Versions:: Each component can optionally have one or more versions.  We should only declare versions where it makes sense to keep documentation for the old version accessible online.
Modules:: https://docs.antora.org/antora/latest/module-directories/[Antora describes] modules as "primarily an organization tool for the writer". So far we haven't used them, so everything is using the default `ROOT` module.

Each language has its own playbook.  Each playbook specifies which components and versions are part of the documentation.  See link:./tech-docs-en-playbook.yml[tech-docs-en-playbook.yml] for the English playbook.  The `content.sources` with a `url` of `.` are in this Git repository, and `HEAD` shows the current (i.e. main) branch is used to provide a single version.  The other components (`git@github.com…`) are from other Git repositories, and some have multiple versions shown in `branches`.

Determining how individual pages should be arranged into components (and potentially modules) is not clear.
It may make translators' work easier if they can aim to translate entire components/modules.

=== Within a component version

A version of a component is defined by its `antora.yml` descriptor file, which should be present at the location specified in `{url}/{start_path}` from the playbook's `content.sources` section.  For example, the https://techdocs.gbif.org/en/data-publishing/[_Data Publishing_] component has its descriptor file in this repository at link:./en/data-publishing/antora.yml[en/data-publishing/antora.yml]:

// If this were part of the real documentation, we could use an 'include:' directive to embed the file.  However, GitHub blocks these
// for security reasons.  See https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/#using-include-directives-in-source-blocks

[,yaml]
----
name: data-publishing
title: Data Publishing
version: ~
nav:
- modules/ROOT/nav.adoc
----

The `name` is the identifier for the component used in links and URLs.  The `title` is used for display.  A `version` of `~` means "no versions".

`nav` sets the left-bar navigation menu.  The content of the linked file is an Asciidoctor unordered list.

=== Further reading

It's probably worth looking at these pages in the Antora and Asciidoctor documentation:

* https://docs.antora.org/antora/latest/family-directories/[Family directories], to see where files for individual pages, images, attachments (downloads) etc. should be stored
* https://docs.antora.org/antora/latest/page/xref/[Xref macros and page links] and https://docs.antora.org/antora/latest/page/page-links/[create page links] to see how to make links within a page, between pages in the same module, different modules, different versions and different components.
* The https://docs.antora.org/[Antora documentation] and the https://docs.asciidoctor.org/asciidoc/latest/[Asciidoctor documentation].

=== Special pages

==== Home page

The English home page, https://techdocs.gbif.org/en/, is a component called `ROOT`, which is a special name where `ROOT` doesn't show in links or URLs.  Reserve pages in this section for the home page and very general pages about the whole manual.

Exactly what belongs in the home module isn't very clear.
It will be easier to work out once we have more documentation written.
Perhaps a small amount of key information that we'd expect to be fully translated into supported languages?

==== OpenAPI

Auto-generated pages from https://www.openapis.org/[OpenAPI] endpoints are generated for our webservices.

The script link:fetch-openapi.py[`fetch-openapi.py`] retrieves the OpenAPI definitions, and makes some rearrangements — some sections of the Registry are better documented as part of the Occurrences module.  It also defines what is included in the "Key methods" version of the Registry, edit the script to add/remove methods.

There are three versions of the `openapi` Antora module, stored in link:en/openapi[`en/openapi`], link:en/openapi-v1[`en/openapi-v1`] and link:en/openapi-v2[`en/openapi-v2`]. This structure is only visible to the user in the resulting URLs, and in Antora's version menu which allows access to the old Maps V1 documentation. This structure will be more useful during and after our transition to V2 for the other modules.

It does mean links to the OpenAPI documentation need the version to be specified.  See link:en/openapi/modules/ROOT/nav.adoc[`nav.adoc`] for the current links.

=== Site theme

The overall design of the site is controlled by a theme, https://github.com/gbif/tech-docs-theme[tech-docs-theme].  That sets the colours, fonts etc and adds the "Search docs" functionality.

Changing the site menus (on the green bar) is done by overriding the theme.  Start at link:./supplemental_ui/partials/header-content.hbs[supplemental_ui/partials/header-content.hbs] and copy + paste until you have what you want :-) (but remember pushing changes rebuilds the live site).

== Additional Asciidoc syntax

In general editors should refer to the https://docs.asciidoctor.org/asciidoc/[Asciidoctor documentation] and the https://docs.antora.org/antora/[Antora documentation].  Special syntax is used for:

=== OpenAPI pages

These are shown using Swagger, and a special page layout present in the site theme (see https://github.com/gbif/tech-docs-theme/blob/main/src/layouts/swagger.hbs[swagger.hbs] for the source).

The OpenAPI source link:./fetch-openapi.py[is retrieved] whenever webservices are deployed, so it is always up-to-date.  This is done on all environments; techdocs.gbif.org documents api.gbif.org and techdocs.gbif-uat.org documents api.gbif-uat.org.

=== Darwin Core Archive term tables

These are generated when the site is built using link:./en/data-use/modules/ROOT/partials/download-terms-tables.py[this Python script]. The script generates a https://docs.antora.org/antora/latest/page/partials/[partial], which is included in the main pages.

=== UAT-only pages

Pages or parts of pages can be excluded from techdocs.gbif.org while they are under development.  This also excludes them from search results.

//
// If you are reading this file in a text editor, note the backslashes are not required
// — they are to avoid the text being hidden when displayed on GitHub.
//

.Hiding a whole page from techdocs.gbif.org — this **MUST** be at the start of the file
[source,asciidoc]
----
\ifeval::["{env}" == "prod"]
:page-unpublish:
\endif::[]

= Page title

\include::ROOT::partial$under-construction.adoc[]
----

.Hiding part of a page
[source,asciidoc]
....
\ifeval::["{env}" != "prod"]
On the UAT system …
\endif::[]
....

.Hiding an entry from the navigation (nav.adoc)
[source,asciidoc]
----
\ifeval::["{env}" != "prod"]
* xref:page-name.adoc[Page title **UAT**]
\endif::[]
----

== Building

The site builds in Jenkins every time it is modified, see the https://builds.gbif.org/job/tech-docs/lastBuild/console[status] and badge above.  To build it locally, the simplest method is to use Docker.  See the https://docs.docker.com/[Docker documentation] for installation on https://docs.docker.com/desktop/install/linux-install/[Linux], https://docs.docker.com/desktop/install/mac-install/[Mac] and https://docs.docker.com/desktop/install/windows-install/[Windows].

For routine use when authoring documentation, build just the English documentation and omit the search functionality. This uses a special cut-down playbook without some of the configuration suitable for a webserver:

[,sh]
----
./build-local-documentation.sh
----

To build English and Spanish and with the search function, and suitable for a webserver, run:

[,sh]
----
docker run --rm -t --user $(id -u) --volume $PWD:/antora:Z --env HOME=/antora antora/antora:3.0.1 npm i @antora/lunr-extension
for lang in en es; do
    docker run --rm -t --user $(id -u) --volume $PWD:/antora:Z antora/antora:3.0.1 tech-docs-$lang-playbook.yml
done
----

There is also internal documentation defined in `internal.yml`.  This is built _before_ the public documentation, which overwrites the CSS/JS output but leaves the internal documentation folders in-place.  Therefore, the internal documentation doesn't appear in the public component selector.

Please explore the Antora documentation for alternative methods for building, but they are all going to be more effort than installing Docker.
