site:
  title: Technical Documentation (S Chinese)
  start_page: ROOT::index.adoc
  keys:
    language: zh
content:
  sources:
    - url: .
      start_path: ./zh/home
      branches: HEAD
    - url: .
      start_path: ./zh/data-publishing
      branches: HEAD
    - url: .
      start_path: ./zh/data-processing
      branches: HEAD
    - url: .
      start_path: ./zh/data-use
      branches: HEAD
    - url: .
      start_path: ./zh/cloud-services
      branches: HEAD
    - url: .
      start_path: ./zh/openapi
      branches: HEAD
    - url: .
      start_path: ./zh/openapi-v1
      branches: HEAD
    - url: .
      start_path: ./zh/openapi-v2
      branches: HEAD
    - url: .
      start_path: ./zh/tools
      branches: HEAD
    - url: .
      start_path: ./zh/system-components
      branches: HEAD
    #- url: .
    #  start_path: ./zh/guides
    #  branches: HEAD
    #- url: https://github.com/gbif/ipt.git
    #  branches: [ipt-2.4-docs, master]
    #  edit_url: 'https://github.com/gbif/ipt/edit/master/{path}'
    #  start_path: docs/zh
    #- url: https://github.com/gbif/doc-publishing-dna-derived-data.git
    #  start_path: en
    #  branches: antora
output:
  clean: false
  dir: ./output/zh
runtime:
  fetch: true
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: httpd
asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Page contents'
    language: zh
    null: ␀
antora:
  extensions:
#  - require: '@antora/lunr-extension'
#    index_latest_only: true
#    languages: [zh]
  - require: ./unpublish-flagged-pages.js
