site:
  title: Technical Documentation (Arabic)
  start_page: ROOT::index.adoc
  keys:
    language: ar
content:
  sources:
    - url: .
      start_path: ./ar/home
      branches: HEAD
    - url: .
      start_path: ./ar/data-publishing
      branches: HEAD
    - url: .
      start_path: ./ar/data-processing
      branches: HEAD
    - url: .
      start_path: ./ar/data-use
      branches: HEAD
    - url: .
      start_path: ./ar/cloud-services
      branches: HEAD
    - url: .
      start_path: ./ar/openapi
      branches: HEAD
    - url: .
      start_path: ./ar/openapi-v1
      branches: HEAD
    - url: .
      start_path: ./ar/openapi-v2
      branches: HEAD
    - url: .
      start_path: ./ar/tools
      branches: HEAD
    - url: .
      start_path: ./ar/system-components
      branches: HEAD
    #- url: .
    #  start_path: ./ar/guides
    #  branches: HEAD
    #- url: https://github.com/gbif/ipt.git
    #  branches: [ipt-2.4-docs, master]
    #  edit_url: 'https://github.com/gbif/ipt/edit/master/{path}'
    #  start_path: docs/ar
    #- url: https://github.com/gbif/doc-publishing-dna-derived-data.git
    #  start_path: en
    #  branches: antora
output:
  clean: false
  dir: ./output/ar
runtime:
  fetch: true
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  redirect_facility: httpd
asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Page contents'
    language: ar
    null: ␀
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [ar]
  - require: ./unpublish-flagged-pages.js
