site:
  title: GBIF Technical Documentation
  url: https://tech-docs.gbif-dev.org
  start_page: ROOT::index.adoc
  keys:
    language: es
content:
  sources:
    - url: .
      start_path: ./es/home
      branches: HEAD
    - url: https://github.com/gbif/ipt.git
      branches: [ipt-2.4.2-docs, generated-translations-master]
      start_path: docs/es
      edit_url: '/es/ipt/2.5/translations'
output:
  clean: true
  dir: ./output/es
runtime:
  fetch: false
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
urls:
  html_extension_style: drop
  # TODO: Apache configuration
  latest_version_segment_strategy: redirect:from
  latest_version_segment: current
  redirect_facility: httpd
asciidoc:
  attributes:
    page-pagination: yes
    language: es
    null: ␀
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [es]
