= Occurrence image API

GBIF run an image crop-and-resize server and cache to support display of occurrence images on www.gbif.org and other uses.

Note that occurrence images may be licensed under more restrictive terms than other occurrence data.  Refer to the relevant terms in the multimedia extensions, or contact the publisher of the dataset.

== Usage

The server runs https://www.thumbor.org[Thumbor], so for general instructions on cropping, resizing and so on see the https://thumbor.readthedocs.io/[Thumbor documentation].

To retrieve an occurrence image, use a URL of the form

----
https://api.gbif.org/v1/image/cache/occurrence/[gbifId]/media/[md5sum(identifier)]
----

where `[gbifId]` is the `key` of the occurrence, and `[md5sum(identifier)]` is the MD5 checksum in hexadecimal format of the `.media[].identifier` URL.

For example, the occurrence https://api.gbif.org/v1/occurrence/2005380410[2005380410] with media identifier `https://inaturalist-open-data.s3.amazonaws.com/photos/31610070/original.jpg` may be accessed (and optionally resized, cropped and so on) with URLs like

----
https://api.gbif.org/v1/image/cache/occurrence/2005380410/media/568639b65b65ddb9090d3d6ef1abce14
https://api.gbif.org/v1/image/cache/200x/occurrence/2005380410/media/568639b65b65ddb9090d3d6ef1abce14
----

image::https://api.gbif.org/v1/image/cache/200x/occurrence/2005380410/media/568639b65b65ddb9090d3d6ef1abce14[Image example]

== Limitations

*Please limit scripted usage of this API to a single HTTP connection.*

The maximum image resolution available through the server is 1200×1200px.  The JPEG quality of larger images is limited to 85.  For the highest resolution image, download from the publisher's server.
