= Dataset classes
ifeval::["{env}" == "prod"]
:page-unpublish:
endif::[]

Note: this page is currently under development
  
Datasets shared with GBIF can be published in four different formats:

[%autowidth.stretch]
|===
|Dataset type |Content 

|Metadata-only
|datasets describing **undigitized** resources like those in natural history and other collections

|https://rs.gbif.org/core/dwc_taxon_2024-02-19.xml[Checklist]
|a **catalogue** or list of named organisms, or taxa

|https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml[Occurrence]
|the evidence of the **occurrence of a species** (or other taxon) at a particular place on a specified date. Occurrence datasets make up the core of data published through GBIF.org

|https://rs.gbif.org/core/dwc_event_2024-02-19.xml[Sampling event]
|offering evidence that a species occurred at a given location and date, but also making it possible to **assess community composition** for broader taxonomic groups or even the **abundance of species** at multiple times and places
  
|===

The four classes of datasets supported by GBIF start simply and become progressively richer, more structured and more complex. This https://data-blog.gbif.org/post/choose-dataset-type/[blog post] can help you choose a dataset class if you are new to GBIF publishing.

Some fields are strongly recommended to be included in the different dataset classes and some may be required if the dataset is funded through a programme operated by GBIF (e.g. https://www.gbif.org/programme/82243[BID], https://www.gbif.org/programme/82629[BIFA], https://www.gbif.org/programme/82219[CESP]). 
                                                                                                                                                                             
Data quality requirements for each dataset class and the GBIF operated programmes are documented xref:data-quality-recommendations.adoc[here].
