ifeval::["{env}" == "prod"] 

:page-unpublish: 

endif::[] 

  

= Processing of Taxonomic Identifiers in GBIF 


include::ROOT::partial$under-construction.adoc[] 

GBIF processes taxonomic identifiers that are provided on the DwC elements _scientificNameID_, _taxonID_ and _taxonConceptID_, when these identifiers belong to any of the identifier schemes available. The identifiers are retrieved from ChecklistBank and linked to taxa in the checklist, currently the schemes available are: 

* https://artfakta.se/metadata/dyntaxa[Dyntaxa]: A taxonomic database of the names of Swedish organisms, contains information on current classification, recommended names and commonly used synonyms and misused names. It should follow the format: `+^(?:dyntaxa|artfakta|urn:lsid:dyntaxa.se:Taxon):(\\d+)`
* https://www.ipni.org/[IPNI]: The International Plant Names Index (IPNI) is a nomenclatural index of names of vascular plants published under the Code of Nomenclature for algae, fungi and plants (ICN).  It should follow the format: `+^(?:ipni|urn:lsid:ipni.org:names):(\\d+-[1-3])`
* https://www.itis.gov/p[ITIS]: The Integrated Taxonomic Information System, an authoritative taxonomic information on plants, animals, fungi, and microbes of North America and the world. It should follow the format: `+^(?:itis|tsn:)(\\d+)`
* https://www.nhm.ac.uk/our-science/data/uk-species/index[UK Species Inventory]: A database of all UK wildlife, it provides the taxonomic foundation for most biological recording and analysis systems for the UK. It should follow the format: `+^(?:uksi|nhm):((?:NHMSYS|NBNSYS)\\d{10})`
* https://www.marinespecies.org/index.php[WoRMs]: The World Register of Marine Species (WoRMS) aim to provide an authoritative and comprehensive list of names of marine organisms, including information on synonymy. It should follow the format: `+^(?:marinespecies|worms|aphia|urn:lsid:marinespecies.org:taxname):(\\d+)`

When both an identifier field and a _scientificName_ are provided, the identifiers will be used first for matching, and if there is more than one identifier present, the information on _taxonID_ will take precedence. A match will also be made using the scientificName and a comparison will be made between the two matches. 

When there are identifiers present, the following issues could arise:

* ‘Scientific name and ID inconsistent’: When the information in _scientificName_ and any of the identifiers do not agree. 
* ‘Scientific name ID not found’, ‘Taxon concept ID not found’ or ‘Taxon ID not found’: An identifier is provided and match the known pattern of the schemes available, but it is not found in the associated checklist.
* ‘Taxon match scientific name ID ignored’, ‘Taxon match taxon concept ID ignored’ or ‘Taxon match taxon ID ignored’: An identifier is provided but does not match the known pattern of the schemes available. 
* ‘Taxon match name and ID ambiguous‘: When the concept was found using any of the identifiers, but it differs from what would have been found if the classification names on the record were used.

You can read the full description of the issues here: https://techdocs.gbif.org/en/data-use/occurrence-issues-and-flags#taxonomic-issues[Taxonomic issues] and the detailed technical information about Taxonomic indexes is available on: https://techdocs.gbif.org/en/data-processing/taxonomy-interpretation#taxonomic-indexes[Taxonomy interpretation - Taxonomic indexes].
