ifeval::["{env}" == "prod"] 

:page-unpublish: 

endif::[] 

  

= Processing of Taxonomic Identifiers in GBIF 


include::ROOT::partial$under-construction.adoc[] 

GBIF processes taxonomic identifiers that are provided on the DwC elements _scientificNameID_, _taxonID_ and _taxonConceptID_, when these identifiers belong to any of the identifier schemes available.  

Currently the schemes available are: 

* https://artfakta.se/metadata/dyntaxa[Dyntaxa]: A taxonomic database of the names of Swedish organisms, contains information on current classification, recommended names and commonly used synonyms and misused names. 
* https://www.ipni.org/[IPNI]: The International Plant Names Index (IPNI) is a nomenclatural index of names of vascular plants published under the Code of Nomenclature for algae, fungi and plants (ICN). 
* https://www.itis.gov/p[ITIS]: The Integrated Taxonomic Information System, an authoritative taxonomic information on plants, animals, fungi, and microbes of North America and the world. 
* https://www.nhm.ac.uk/our-science/data/uk-species/index[UK Species Inventory]: A database of all UK wildlife, it provides the taxonomic foundation for most biological recording and analysis systems for the UK. 
* https://www.marinespecies.org/index.php[WoRMs]: The World Register of Marine Species (WoRMS) aim to provide an authoritative and comprehensive list of names of marine organisms, including information on synonymy. 

If both an identifier field and a _scientificName_ are provided, the identifier field will be used first for matching. A match will also be made using the scientificName and a comparison will be made between the two matches. If they do not agree, a https://techdocs.gbif.org/en/data-use/occurrence-issues-and-flags#taxonomic-issues[flag] will be issued in response to indicate the inconsistency, the possible flags are ‘Scientific name and ID inconsistent’. 


If an identifier is provided and match the known pattern of the schemes available, but it is not found in the associated checklist a flag will be issued to indicate that it is missing, the possible flags are ‘Scientific name ID not found’, ‘Taxon concept ID not found’ and ‘Taxon ID not found’. This may indicate a poorly formatted identifier or may be caused by a newly created ID that isn’t yet known in the version of the published checklist. 


If an identifier is provided, but does not match the known pattern of the schemes available, a flag will be issued to indicate that it was ignored, the possible flags are ‘Taxon match scientific name ID ignored’, ‘Taxon match taxon concept ID ignored’ and ‘Taxon match taxon ID ignored’. 


They detailed technical information about Taxonomic indexes is available on: https://techdocs.gbif.org/en/data-processing/taxonomy-interpretation#taxonomic-indexes[Taxonomy interpretation - Taxonomic indexes]
